[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rag"
version = "0.1"
requires-python = ">=3.12,<3.13"
description = "A Python package for RAG utilities"
authors = [{name = "Witold Nowogrski, Micha Dyrek, Mateusz Walczak"}]
dependencies = [
    "bs4==0.0.2",
    "dotenv==0.9.9",
    "html2text==2025.4.15",
    "langchain==0.3.25",
    "langchain-core==0.3.59",
    "langchain-google-genai==2.0.10",
    "langchain-text-splitters==0.3.8",
    "langgraph==0.4.3",
    "markdown==3.8",
    "matplotlib==3.10.3",
    "networkx==3.4.2",
    "nltk==3.9.1",
    "numpy==1.26.4",
    "pandas==2.0.3",
    "pdf2image==1.17.0",
    "plotly==6.1.0",
    "pydantic==2.11.4",
    "pymilvus==2.5.8",
    "pymongo==4.13.2",
    "pytesseract==0.3.13",
    "rank-bm25==0.2.2",
    "requests==2.32.3",
    "scikit-learn>=1.3.2",
    "seaborn==0.13.2",
    "sentence-transformers==3.4.1",
    "streamlit==1.43.2",
    "torch==2.6.0",
    "tqdm==4.67.1",
]

[tool.setuptools.packages.find]
include = ["chat_graph", "datastore", "web_scraping"]

[tool.deptry.package_module_name_map]
bs4 = ["bs4"]
dotenv = ["dotenv"]
html2text = ["html2text"]
langchain = ["langchain"]
langchain-core = ["langchain_core"]
langchain-google-genai = ["langchain_google_genai"]
langchain-text-splitters = ["langchain_text_splitters"]
langgraph = ["langgraph"]
markdown = ["markdown"]
matplotlib = ["matplotlib"]
networkx = ["networkx"]
pdf2image = ["pdf2image"]
plotly = ["plotly"]
pydantic = ["pydantic"]
pymilvus = ["pymilvus"]
pymongo = ["pymongo"]
pytesseract = ["pytesseract"]
scikit-learn = ["sklearn"]
seaborn = ["seaborn"]
sentence-transformers = ["sentence_transformers"]
streamlit = ["streamlit"]
torch = ["torch"]