from typing import List, TypedDict

from langchain_core.messages import BaseMessage
from langchain_core.documents import Document


class ChatState(TypedDict):
    """
    Represents the state of the chat workflow.

    Attributes:
        messages (List[BaseMessage]): Chat history.
        questions (List[str]):
            A list of questions generated by QuestionsGenerationAgent to query the knowledge base or vector store.
        use_rag (bool):
            A flag indicating whether to use the RAG or answer directly to the last user message.
        retrieved_docs (List[List[Document]]):
            A nested list of retrieved documents for each generated question.
        web_search_flags (List[bool]): Flags indicating whether the retrieved documents for each question
            lack sufficient information and require external web search.
        summaries (List[str]):
            Summaries generated from the retrieved documents or web search results corresponding to each question.

    """
    messages: List[BaseMessage]
    questions: List[str]
    use_rag: bool
    retrieved_docs: List[List[Document]]
    web_search_flags: List[bool]
    summaries: List[str]