name: Chat AGH end to end test

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
         pip install pytest pytest-cov

#    - name: Run Pylint
#      run: |
#        echo "Running pylint check..."
#        pylint --disable=missing-module-docstring  chat_graph

    - name: Download NLTK punkt data
      run: |
        python -m nltk.downloader punkt

    - name: Run test
      env:
        GEMINI_API_KEYS: ${{ secrets.GEMINI_API_KEYS }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        pytest --cov=./ --cov-report=xml
